Don't include users with zero posts
hackclub/scrapbook pull request #310
Opened 2022-05-01 04:33 UTC by exu3

Not sure if this will break anything, but this PR updates the /api/users route to only return users with at least 1 scrapbook post. Previously, it returned all (full) members of the Slack.

Response is under Vercel's limit of 4MB:
<img width="349" alt="Screen Shot 2022-04-30 at 21 29 23" src="https://user-images.githubusercontent.com/72365100/166132312-5420b50a-d589-4324-ba78-d6b3cd02eccf.png">

Should fix #309

2022-05-01 04:43 UTC, sampoder commented
This is a good idea and the approach I think we have to take. However, I would prefer not to modify the function directly. Instead I think we should add a param to the function called: `where` that is placed in the Prisma query but defaults to `null`. We also need to consider if we could have a stripped down function to use in some cases that only responds with usernames for use on custom domains.

2022-05-01 04:43 UTC, sampoder requested changes
I hope that makes sense? I just want to make sure we don't break anything

2022-05-01 18:20 UTC, exu3 commented
Ah good point; not modifying the function directly is a good idea

> I think we should add a param to the function called: where that is placed in the Prisma query but defaults to null.

I'm not quite sure what you mean by this. Possibly because I'm pretty new to Prisma. Is there an example of this in another api route?

> We also need to consider if we could have a stripped down function to use in some cases that only responds with usernames for use on custom domains.

I think this would be a good idea.

2022-05-02 01:50 UTC, sampoder approved these changes
👍 Thanks Ella!

2022-05-02 01:50 UTC, merged